#Version 0.1
blueprint:
  name: Licht per Ping-Sensor
  description: Licht basierend auf PING-Sensor Ein-/Ausschalten.
  domain: automation
  input:
    ping_entity:
      name: PING-Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: connectivity
    light_target:
      name: Licht
      selector:
        target:
          entity:
            domain: light          

# If ping is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input ping_entity
  to: "on"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
  - alias: "Wait until there is no ping from device"
    wait_for_trigger:
      platform: state
      entity_id: !input ping_entity
      to: "off"
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
